### PR TITLE
Implement alterF

### PR DESCRIPTION
**Pull request by ollef**
This is in containers since version 0.5.8 so shouldn't cause any versioning trouble.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Oh, cool. Have you tested the new operation?

**Comment by ollef** [comment]
I've tried it a little bit in a project, yeah. :)

**Comment by Mikolaj** [comment]
Thank you. Any particular urgency about releasing this on Hackage?

**Comment by ollef** [comment]
Thanks! Nah, no rush from my end.

And thanks for the package by the way!

**Comment by Mikolaj** [comment]
You are welcome, though I'm just a punk standing on the shoulders of giants. :)

**Pull request merged**
